management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/testdb
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8090'